In [1]:
from sklearn.pipeline import Pipeline

In [7]:
# feature Scaling
from sklearn.preprocessing import StandardScaler

In [13]:
#estimator
from sklearn.linear_model import LogisticRegression

In [17]:
steps=[('Standard_Scaler',StandardScaler()),('classifier',LogisticRegression())]


In [19]:
steps

[('Standard_Scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [21]:
Pipeline(steps)

Pipeline(steps=[('Standard_Scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [23]:
pipe=Pipeline(steps)

In [27]:
## Visualize the pipeline
from sklearn import set_config


In [29]:
set_config(display='diagram')

In [31]:
pipe


Pipeline(steps=[('Standard_Scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [33]:
#creating a dataset
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [35]:
X.shape

(1000, 20)

In [37]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [41]:
X_train

array([[ 1.37467566,  1.77994742,  1.87308601, ..., -0.14500715,
         0.39974139,  0.50827464],
       [ 0.03035916,  0.61893175, -0.16604328, ..., -0.23810673,
         1.2900044 ,  0.62397109],
       [ 0.4226894 ,  0.21249372, -1.85465071, ...,  1.27021738,
         1.13216848,  1.15132292],
       ...,
       [ 0.03435075,  1.44919158, -0.25095797, ...,  0.43486779,
        -1.19633332,  1.18310834],
       [-0.78422482, -0.48925335, -1.09338293, ..., -1.77103585,
        -0.79978537,  0.71528641],
       [-1.41941416, -0.45191175,  1.54209811, ..., -0.42671123,
        -1.05065728,  0.94580531]])

In [43]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('Standard_Scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [49]:
y_pred= pipe.predict(X_test)

In [51]:
y_pred

array([0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,

### example-2Displaying a pipeline with standard scaler, dimesnionality reduction and then estimator

In [63]:
from sklearn.decomposition import PCA


In [65]:
from sklearn.svm import SVC


In [67]:
steps=[('scaling',StandardScaler()),('PCA',PCA(n_components=3)),('SVC',SVC())]

In [69]:
steps

[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)), ('SVC', SVC())]

In [83]:
pipe2=Pipeline(steps)

In [79]:
pipe2['scaling'].fit_transform

<bound method TransformerMixin.fit_transform of StandardScaler()>

In [81]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [87]:
pipe2.predict(X_train)

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,

### Complex examples of columns transformer

In [93]:
from sklearn.impute import SimpleImputer
import numpy as np

In [97]:
# numerical processing pipeline

numeric_processor=Pipeline(
    steps=[('impuatation_mean',SimpleImputer(missing_values=np.nan,strategy='mean')),('scaler',StandardScaler())]
)

In [101]:
## categorical processing
from sklearn.preprocessing import OneHotEncoder
categ_processor=Pipeline(
    steps=[('impuatation_constant',SimpleImputer(fill_value='missing',strategy='constant')),('onehot',OneHotEncoder())]
)

In [103]:
categ_processor

Pipeline(steps=[('impuatation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder())])

## combine the pipeline
## combine processing technqiues

In [105]:
from sklearn.compose import ColumnTransformer

In [107]:
preprocessor= ColumnTransformer(
    [('catrgorical',categ_processor,['gender','city']),
    ('numerical',numeric_processor,['age,''height'])       ]
    
)

In [109]:
preprocessor

ColumnTransformer(transformers=[('catrgorical',
                                 Pipeline(steps=[('impuatation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot', OneHotEncoder())]),
                                 ['gender', 'city']),
                                ('numerical',
                                 Pipeline(steps=[('impuatation_mean',
                                                  SimpleImputer()),
                                                 ('scalar', StandardScaler())]),
                                 ['age,height'])])

## add estiamtor

In [115]:
from sklearn.pipeline import make_pipeline

In [117]:
make_pipeline(preprocessor,LogisticRegression())

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('catrgorical',
                                                  Pipeline(steps=[('impuatation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder())]),
                                                  ['gender', 'city']),
                                                 ('numerical',
                                                  Pipeline(steps=[('impuatation_mean',
                                                                   SimpleImputer()),
                                                                  ('scalar',
                                                                   StandardScaler())]),
                                                  ['age,height'])])),
                ('logisticregression', LogisticRegression())])